## Append samples of your project ##
resources:
- v1_podprofile.yaml
- v1_job.yaml
- v1_cronjob.yaml
- v1_cronjobprofile.yaml
- v2_jobprofile.yaml
- v2_cronjob.yaml
- v2_job.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
