apiVersion: pixiv.net/v1
kind: CronJobProfile
metadata:
  labels:
    app.kubernetes.io/name: k8s-job-wrapper
    app.kubernetes.io/managed-by: kustomize
  name: cronjobprofile-sample
spec:
  # TODO(user): Add fields here
