---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: cronjobprofiles.pixiv.net
spec:
  group: pixiv.net
  names:
    kind: CronJobProfile
    listKind: CronJobProfileList
    plural: cronjobprofiles
    singular: cronjobprofile
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: CronJobProfile is the Schema for the cronjobprofiles API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of CronJobProfile
            properties:
              template:
                description: Template describes the cronjobs that will be created.
                properties:
                  cronJobParams:
                    description: '`cronjob.v1.batch.spec` configuration options.'
                    properties:
                      concurrencyPolicy:
                        description: |-
                          Specifies how to treat concurrent executions of a Job.
                          Valid values are:

                          - "Allow" (default): allows CronJobs to run concurrently;
                          - "Forbid": forbids concurrent runs, skipping next run if previous run hasn't finished yet;
                          - "Replace": cancels currently running job and replaces it with a new one
                        type: string
                      failedJobsHistoryLimit:
                        description: |-
                          The number of failed finished jobs to retain.
                          This is a pointer to distinguish between explicit zero and not specified.
                          Defaults to 1.
                        format: int32
                        type: integer
                      schedule:
                        description: The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron.
                        type: string
                      startingDeadlineSeconds:
                        description: |-
                          Optional deadline in seconds for starting the job if it misses scheduled
                          time for any reason.  Missed jobs executions will be counted as failed ones.
                        format: int64
                        type: integer
                      successfulJobsHistoryLimit:
                        description: |-
                          The number of successful finished jobs to retain.
                          This is a pointer to distinguish between explicit zero and not specified.
                          Defaults to 3.
                        format: int32
                        type: integer
                      suspend:
                        description: |-
                          This flag tells the controller to suspend subsequent executions, it does
                          not apply to already started executions.  Defaults to false.
                        type: boolean
                      timeZone:
                        description: |-
                          The time zone name for the given schedule, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
                          If not specified, this will default to the time zone of the kube-controller-manager process.
                          The set of valid time zone names and the time zone offset is loaded from the system-wide time zone
                          database by the API server during CronJob validation and the controller manager during execution.
                          If no system-wide time zone database can be found a bundled version of the database is used instead.
                          If the time zone name becomes invalid during the lifetime of a CronJob or due to a change in host
                          configuration, the controller will stop creating new new Jobs and will create a system event with the
                          reason UnknownTimeZone.
                          More information can be found in https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones
                        type: string
                    required:
                    - schedule
                    type: object
                  metadata:
                    description: |-
                      Standard object's metadata.
                      More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
                    type: object
                type: object
            required:
            - template
            type: object
          status:
            description: status defines the observed state of CronJobProfile
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
